name: Deploy Zou to staging environment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: zou
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          run:  sudo docker pull postgres
                sudo docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres
                sudo docker pull redis
                sudo docker run --name redis -p 6379:6379 -d redis
                sudo apt-get install ffmpeg
                git clone git@github.com:cgwire/zou.git
                pip install virtualenvwrapper
                mkvirtualenv zou
                workon zou
                pip install -r requirements.txt
                curl --output apispec_1.json https://nehmath.github.io/zou-nehmat/apispec_1.json