name: Deploy Zou to staging environment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: zou
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
      - run:  sudo docker pull postgres
      - run:  sudo docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres
      - run:  sudo docker pull redis
      - run:  sudo docker run --name redis -p 6379:6379 -d redis
      - run:  sudo apt-get install ffmpeg
      - run:  git clone git@github.com:cgwire/zou.git
      - run:  pip install virtualenvwrapper
      - run:  mkvirtualenv zou
      - run:  workon zou
      - run:  pip install -r requirements.txt
      - run:  curl --output apispec_1.json https://nehmath.github.io/zou-nehmat/apispec_1.json